# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My Cornhole'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "cornholius"
      ]'
      custom_config: '["#define MIRYOKU_KLUDGE_BOTTOMROWCOMBOS\n#define U_TAPPING_TERM 175\n#define MIRYOKU_KLUDGE_SOFT_OFF"]'
      kconfig: '["CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16\nCONFIG_ZMK_PM_SOFT_OFF=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=86400000\nCONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10\nCONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10"]'
      branches: '["zmkfirmware/zmk/main"]'
      alphas: '["qwerty"]'
